# Generated by Django 3.1 on 2020-08-28 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_handler', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testing',
        ),
    ]
